//
//  CallCommand.hpp
//  jasl
//
//  Created by Ben Jones on on 10/03/2015.
//  Copyright (c) 2015 Ben Jones. All rights reserved.
//

#include "CallCommand.hpp"
#include "../CommandInterpretor.hpp"
#include <vector>

namespace jasl 
{
    CallCommand::CallCommand(Function &func_, OptionalOutputStream const &output)
    : Command(func_, output)
    {
    }

    bool CallCommand::execute()
    {
        std::string functionName; 
        (void)m_func.getValueA<std::string>(functionName);

        // check if call statement expecting a returnable in
        // which case we search for returnable rather than block
        // functions
        std::string returnSymbol;
        if(m_func.getValueB<std::string>(returnSymbol)) {
            return searchForFunction(functionName, 
                                     "returnable",
                                     returnSymbol);
        }

        return searchForFunction(functionName);
    }

    bool CallCommand::searchForFunction(std::string &functionName,
                                        std::string const &kind,
                                        std::string const &returnSymbol)
    {
        // First get all subroutines
        std::string &scriptString = VarCache::script;
        CommandInterpretor ci;
        auto functions = ci.parseStringCollection(scriptString);

        // Find all functions that are block functions
        decltype(functions) matched;
        for(auto &f : functions) {
            std::string funcName;
            if (f.name.find(kind) != std::string::npos) {
                matched.push_back(f);
            }
        }

        // Second, search for block with given name
        auto it = std::find_if(std::begin(matched), std::end(matched), [&](Function &f) { 

            std::string name;
            if(kind == "block") {
                (void)f.getValueA<std::string>(name);
            } else if(kind == "returnable") {
                (void)f.getValueB<std::string>(name);
            }
            return name == functionName;
        });

        // function was found so execute it
        if (it != std::end(matched)) {

            return parseCommand(*it, kind, returnSymbol);
        } 
        return false;
    }

    bool CallCommand::parseCommand(Function &function, 
                                   std::string const &kind,
                                   std::string const &returnSymbol)
    {
        CommandInterpretor ci;
        (void)ci.interpretFunc(function, m_outputStream);

        // now set result of function if returnable type
        if(kind == "returnable") {

            // what is the return type?
            std::string type;
            (void)function.getValueA<std::string>(type);

            // what is the name of the returned variable
            std::string returnName;
            (void)function.getValueC<std::string>(returnName);

            // now set the returned variable in the returnSymbol
            // and erase the original function result
            if(type == "integer") {
                auto result = VarCache::getInt(returnName);
                VarCache::setInt(returnSymbol, *result);
            } else if(type == "decimal") {
                auto result = VarCache::getDouble(returnName);
                VarCache::setDouble(returnSymbol, *result);
            } else if(type == "string") {
                auto result = VarCache::getString(returnName);
                VarCache::setString(returnSymbol, *result);
            } else if(type == "boolean") {
                auto result = VarCache::getBool(returnName);
                VarCache::setBool(returnSymbol, *result);
            } else if(type == "list") {
                auto result = VarCache::getList(returnName);
                VarCache::setList(returnSymbol, *result);
            } else {
                setLastErrorMessage("call returnable: unknown return type");
                return false;
            }

            // to introduce some notion of variable locality,
            // erase the variable generated by the function itself
            VarCache::eraseValue(returnName);

        }

        return true;
    }
}